[package]
name = "roc-fuzz"
version = "0.0.1"
authors = ["Brendan Hansknecht"]
license = "MIT"
edition = "2021"
links = "roc-fuzz"

[dependencies]
roc_std = { path = "../roc/crates/roc_std" }
libc = "0.2"

[build-dependencies]
glob = "0.3"

[workspace]
